### ISSUE TITLE
Total time takes into account initialization

### ISSUE THREAD

**Issue by jherrera80** [abulmo/MPerft#5]
"time = -chrono()" should be placed right before starting to search (right after "// root search"), not at declaration, in order to discard initialization and hashtable allocation.

**Comment by abulmo** [comment]
I am not sure if  it is an issue.
The time variable is only used with the (div)ide of loop modes. Under the divide mode, I don't think the time is an important value. The divide mode is useful for debugging, not for benchmarking. Under the loop mode, partial time for each depth, taking only the search duration into account, is also displayed. The total time taking into account the overall time, including initialization, might then add some interesting information.

**Comment by jherrera80** [comment]
Well, one would expect total time to be the sum of all the partial times, especially if you use it to show average nps in the same line, dividing total node count by total time. It is misleading if part of than total time was not spent searching nodes.
