### ISSUE TITLE
Unsigned long long

### ISSUE THREAD

**Issue by jherrera80** [abulmo/MPerft#6]
Unsigned long long should be replaced with uint64_t for consistency (avoiding assignment from uint64_t to unsigned long long).

**Comment by abulmo** [comment]
Printing uint64_t trough string concatenation with PRIu64 is ugly at least and not well supported by some (old) compilers. Assigning an uint64_t to an unsigned long long should not be a problem, as unsigned long long minimal size is 64 bits.
